// src/lib/teams.ts
import type { League, FollowedTeam } from "./types";

/** NBA (30) */
export const NBA_TEAMS: FollowedTeam[] = [
  { league: "nba", teamId: "ATL", name: "Atlanta Hawks" },
  { league: "nba", teamId: "BOS", name: "Boston Celtics" },
  { league: "nba", teamId: "BKN", name: "Brooklyn Nets" },
  { league: "nba", teamId: "CHA", name: "Charlotte Hornets" },
  { league: "nba", teamId: "CHI", name: "Chicago Bulls" },
  { league: "nba", teamId: "CLE", name: "Cleveland Cavaliers" },
  { league: "nba", teamId: "DAL", name: "Dallas Mavericks" },
  { league: "nba", teamId: "DEN", name: "Denver Nuggets" },
  { league: "nba", teamId: "DET", name: "Detroit Pistons" },
  { league: "nba", teamId: "GSW", name: "Golden State Warriors" },
  { league: "nba", teamId: "HOU", name: "Houston Rockets" },
  { league: "nba", teamId: "IND", name: "Indiana Pacers" },
  { league: "nba", teamId: "LAC", name: "LA Clippers" },
  { league: "nba", teamId: "LAL", name: "Los Angeles Lakers" },
  { league: "nba", teamId: "MEM", name: "Memphis Grizzlies" },
  { league: "nba", teamId: "MIA", name: "Miami Heat" },
  { league: "nba", teamId: "MIL", name: "Milwaukee Bucks" },
  { league: "nba", teamId: "MIN", name: "Minnesota Timberwolves" },
  { league: "nba", teamId: "NOP", name: "New Orleans Pelicans" },
  { league: "nba", teamId: "NYK", name: "New York Knicks" },
  { league: "nba", teamId: "OKC", name: "Oklahoma City Thunder" },
  { league: "nba", teamId: "ORL", name: "Orlando Magic" },
  { league: "nba", teamId: "PHI", name: "Philadelphia 76ers" },
  { league: "nba", teamId: "PHX", name: "Phoenix Suns" },
  { league: "nba", teamId: "POR", name: "Portland Trail Blazers" },
  { league: "nba", teamId: "SAC", name: "Sacramento Kings" },
  { league: "nba", teamId: "SAS", name: "San Antonio Spurs" },
  { league: "nba", teamId: "TOR", name: "Toronto Raptors" },
  { league: "nba", teamId: "UTA", name: "Utah Jazz" },
  { league: "nba", teamId: "WAS", name: "Washington Wizards" },
];

/** NFL (32) */
export const NFL_TEAMS: FollowedTeam[] = [
  { league: "nfl", teamId: "ARI", name: "Arizona Cardinals" },
  { league: "nfl", teamId: "ATL", name: "Atlanta Falcons" },
  { league: "nfl", teamId: "BAL", name: "Baltimore Ravens" },
  { league: "nfl", teamId: "BUF", name: "Buffalo Bills" },
  { league: "nfl", teamId: "CAR", name: "Carolina Panthers" },
  { league: "nfl", teamId: "CHI", name: "Chicago Bears" },
  { league: "nfl", teamId: "CIN", name: "Cincinnati Bengals" },
  { league: "nfl", teamId: "CLE", name: "Cleveland Browns" },
  { league: "nfl", teamId: "DAL", name: "Dallas Cowboys" },
  { league: "nfl", teamId: "DEN", name: "Denver Broncos" },
  { league: "nfl", teamId: "DET", name: "Detroit Lions" },
  { league: "nfl", teamId: "GB",  name: "Green Bay Packers" },
  { league: "nfl", teamId: "HOU", name: "Houston Texans" },
  { league: "nfl", teamId: "IND", name: "Indianapolis Colts" },
  { league: "nfl", teamId: "JAX", name: "Jacksonville Jaguars" },
  { league: "nfl", teamId: "KC",  name: "Kansas City Chiefs" },
  { league: "nfl", teamId: "LAC", name: "Los Angeles Chargers" },
  { league: "nfl", teamId: "LAR", name: "Los Angeles Rams" },
  { league: "nfl", teamId: "LV",  name: "Las Vegas Raiders" },
  { league: "nfl", teamId: "MIA", name: "Miami Dolphins" },
  { league: "nfl", teamId: "MIN", name: "Minnesota Vikings" },
  { league: "nfl", teamId: "NE",  name: "New England Patriots" },
  { league: "nfl", teamId: "NO",  name: "New Orleans Saints" },
  { league: "nfl", teamId: "NYG", name: "New York Giants" },
  { league: "nfl", teamId: "NYJ", name: "New York Jets" },
  { league: "nfl", teamId: "PHI", name: "Philadelphia Eagles" },
  { league: "nfl", teamId: "PIT", name: "Pittsburgh Steelers" },
  { league: "nfl", teamId: "SF",  name: "San Francisco 49ers" },
  { league: "nfl", teamId: "SEA", name: "Seattle Seahawks" },
  { league: "nfl", teamId: "TB",  name: "Tampa Bay Buccaneers" },
  { league: "nfl", teamId: "TEN", name: "Tennessee Titans" },
  { league: "nfl", teamId: "WAS", name: "Washington Commanders" },
];

/** MLB (30) */
export const MLB_TEAMS: FollowedTeam[] = [
  { league: "mlb", teamId: "ARI", name: "Arizona Diamondbacks" },
  { league: "mlb", teamId: "ATL", name: "Atlanta Braves" },
  { league: "mlb", teamId: "BAL", name: "Baltimore Orioles" },
  { league: "mlb", teamId: "BOS", name: "Boston Red Sox" },
  { league: "mlb", teamId: "CHC", name: "Chicago Cubs" },
  { league: "mlb", teamId: "CHW", name: "Chicago White Sox" },
  { league: "mlb", teamId: "CIN", name: "Cincinnati Reds" },
  { league: "mlb", teamId: "CLE", name: "Cleveland Guardians" },
  { league: "mlb", teamId: "COL", name: "Colorado Rockies" },
  { league: "mlb", teamId: "DET", name: "Detroit Tigers" },
  { league: "mlb", teamId: "HOU", name: "Houston Astros" },
  { league: "mlb", teamId: "KC",  name: "Kansas City Royals" },
  { league: "mlb", teamId: "LAA", name: "Los Angeles Angels" },
  { league: "mlb", teamId: "LAD", name: "Los Angeles Dodgers" },
  { league: "mlb", teamId: "MIA", name: "Miami Marlins" },
  { league: "mlb", teamId: "MIL", name: "Milwaukee Brewers" },
  { league: "mlb", teamId: "MIN", name: "Minnesota Twins" },
  { league: "mlb", teamId: "NYM", name: "New York Mets" },
  { league: "mlb", teamId: "NYY", name: "New York Yankees" },
  { league: "mlb", teamId: "OAK", name: "Oakland Athletics" },
  { league: "mlb", teamId: "PHI", name: "Philadelphia Phillies" },
  { league: "mlb", teamId: "PIT", name: "Pittsburgh Pirates" },
  { league: "mlb", teamId: "SD",  name: "San Diego Padres" },
  { league: "mlb", teamId: "SEA", name: "Seattle Mariners" },
  { league: "mlb", teamId: "SF",  name: "San Francisco Giants" },
  { league: "mlb", teamId: "STL", name: "St. Louis Cardinals" },
  { league: "mlb", teamId: "TB",  name: "Tampa Bay Rays" },
  { league: "mlb", teamId: "TEX", name: "Texas Rangers" },
  { league: "mlb", teamId: "TOR", name: "Toronto Blue Jays" },
  { league: "mlb", teamId: "WSH", name: "Washington Nationals" },
];

/** NHL (32) */
export const NHL_TEAMS: FollowedTeam[] = [
  { league: "nhl", teamId: "ANA", name: "Anaheim Ducks" },
  { league: "nhl", teamId: "BOS", name: "Boston Bruins" },
  { league: "nhl", teamId: "BUF", name: "Buffalo Sabres" },
  { league: "nhl", teamId: "CAR", name: "Carolina Hurricanes" },
  { league: "nhl", teamId: "CBJ", name: "Columbus Blue Jackets" },
  { league: "nhl", teamId: "CGY", name: "Calgary Flames" },
  { league: "nhl", teamId: "CHI", name: "Chicago Blackhawks" },
  { league: "nhl", teamId: "COL", name: "Colorado Avalanche" },
  { league: "nhl", teamId: "DAL", name: "Dallas Stars" },
  { league: "nhl", teamId: "DET", name: "Detroit Red Wings" },
  { league: "nhl", teamId: "EDM", name: "Edmonton Oilers" },
  { league: "nhl", teamId: "FLA", name: "Florida Panthers" },
  { league: "nhl", teamId: "LAK", name: "Los Angeles Kings" },
  { league: "nhl", teamId: "MIN", name: "Minnesota Wild" },
  { league: "nhl", teamId: "MTL", name: "Montréal Canadiens" },
  { league: "nhl", teamId: "NJD", name: "New Jersey Devils" },
  { league: "nhl", teamId: "NSH", name: "Nashville Predators" },
  { league: "nhl", teamId: "NYI", name: "New York Islanders" },
  { league: "nhl", teamId: "NYR", name: "New York Rangers" },
  { league: "nhl", teamId: "OTT", name: "Ottawa Senators" },
  { league: "nhl", teamId: "PHI", name: "Philadelphia Flyers" },
  { league: "nhl", teamId: "PIT", name: "Pittsburgh Penguins" },
  { league: "nhl", teamId: "SEA", name: "Seattle Kraken" },
  { league: "nhl", teamId: "SJS", name: "San Jose Sharks" },
  { league: "nhl", teamId: "STL", name: "St. Louis Blues" },
  { league: "nhl", teamId: "TBL", name: "Tampa Bay Lightning" },
  { league: "nhl", teamId: "TOR", name: "Toronto Maple Leafs" },
  { league: "nhl", teamId: "UTA", name: "Utah Mammoth" },
  { league: "nhl", teamId: "VAN", name: "Vancouver Canucks" },
  { league: "nhl", teamId: "VGK", name: "Vegas Golden Knights" },
  { league: "nhl", teamId: "WPG", name: "Winnipeg Jets" },
  { league: "nhl", teamId: "WSH", name: "Washington Capitals" },
];

export const LEAGUE_TEAMS: Record<League, FollowedTeam[]> = {
  nba: NBA_TEAMS,
  nfl: NFL_TEAMS,
  mlb: MLB_TEAMS,
  nhl: NHL_TEAMS,
};
